import { PriceItem } from "../data";

export const data: PriceItem[] = [
  {
    name: "Taniec dla 4–6 latków",
    price: "170 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "4–6 lat",
    category: "kidsDance",
  },
  {
    name: "Break Dance",
    price: "170 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "6–8 lat",
    category: "breakdance",
  },
  {
    name: "Balet",
    price: "170 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "",
    category: "ballet",
  },
  {
    name: "Young Generation",
    price: "230 zł",
    frequency: "2x/tyg",
    trending: false,
    age: "7–9 lat",
    category: "youngGeneration",
  },
  {
    name: "Pakiet podstawowy",
    price: "280 zł",
    frequency: "-",
    trending: false,
    age: "",
    category: "foundation",
  },
  {
    name: "Podstawa - treningi hip-hop",
    price: "290 zł",
    frequency: "2x/tyg",
    trending: false,
    age: "",
    category: "hiphop",
  },
  {
    name: "Akrobatyka",
    price: "180 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "4–6 lat",
    category: "acrobatics",
  },
  {
    name: "Akrobatyka",
    price: "180 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "7–9 lat",
    category: "acrobatics",
  },
  {
    name: "Akrobatyka",
    price: "180 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "10–14 lat",
    category: "acrobatics",
  },
  {
    name: "Partnerowanie akro",
    price: "230 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "",
    category: "partnerAcro",
  },
  {
    name: "Formacja dla dorosłych (HIP-HOP/HOUSE)",
    price: "200 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "dorośli",
    category: "adults",
  },
  {
    name: "FEMININE FLOW",
    price: "180 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "dorośli",
    category: "adults",
  },
  {
    name: "Taniec współczesny",
    price: "210 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "8–12 lat",
    category: "modernDance",
  },
  {
    name: "Taniec współczesny",
    price: "220 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "13–18 lat",
    category: "modernDance",
  },
  {
    name: "Taniec współczesny",
    price: "310 zł",
    frequency: "2x/tyg",
    trending: false,
    age: "13–18 lat",
    category: "modernDance",
  },
  {
    name: "Partnerowanie akro",
    price: "230 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "",
    category: "partnerAcro",
  },
  {
    name: "K-POP",
    price: "230 zł",
    frequency: "2x/tyg",
    trending: false,
    age: "",
    category: "kpop",
  },
];