import { PriceItem } from "../data";

export const data: PriceItem[] = [
  {
    name: "Taniec dla 4–6 latków",
    price: "170 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "4",
    maxAge: "6",
    category: "kidsDance",
  },
  {
    name: "Break Dance",
    price: "170 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "6",
    maxAge: "8",
    category: "breakdance",
  },
  {
    name: "Balet",
    price: "170 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "",
    maxAge: "",
    category: "ballet",
  },
  {
    name: "Young Generation",
    price: "230 zł",
    frequency: "2x/tyg",
    trending: false,
    minAge: "7",
    maxAge: "9",
    category: "youngGeneration",
  },
  {
    name: "Pakiet podstawowy",
    price: "280 zł",
    frequency: "-",
    trending: false,
    minAge: "",
    maxAge: "",
    category: "foundation",
  },
  {
    name: "Podstawa - treningi hip-hop",
    price: "290 zł",
    frequency: "2x/tyg",
    trending: false,
    minAge: "",
    maxAge: "",
    category: "hiphop",
  },
  {
    name: "Akrobatyka",
    price: "180 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "4",
    maxAge: "6",
    category: "acrobatics",
  },
  {
    name: "Akrobatyka",
    price: "180 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "7",
    maxAge: "9",
    category: "acrobatics",
  },
  {
    name: "Akrobatyka",
    price: "180 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "10",
    maxAge: "14",
    category: "acrobatics",
  },
  {
    name: "Partnerowanie akro",
    price: "230 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "",
    maxAge: "",
    category: "partnerAcro",
  },
  {
    name: "Formacja dla dorosłych (HIP-HOP/HOUSE)",
    price: "200 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "",
    maxAge: "",
    category: "adults",
  },
  {
    name: "FEMININE FLOW",
    price: "180 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "18",
    maxAge: "99",
    category: "adults",
  },
  {
    name: "Taniec współczesny",
    price: "210 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "8",
    maxAge: "12",
    category: "modernDance",
  },
  {
    name: "Taniec współczesny",
    price: "220 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "13",
    maxAge: "18",
    category: "modernDance",
  },
  {
    name: "Taniec współczesny",
    price: "310 zł",
    frequency: "2x/tyg",
    trending: false,
    minAge: "13",
    maxAge: "18",
    category: "modernDance",
  },
  {
    name: "Partnerowanie akro",
    price: "230 zł",
    frequency: "1x/tyg",
    trending: false,
    minAge: "",
    maxAge: "",
    category: "partnerAcro",
  },
  {
    name: "K-POP",
    price: "230 zł",
    frequency: "2x/tyg",
    trending: false,
    minAge: "",
    maxAge: "",
    category: "kpop",
  },
];
