import { PriceItem } from "../data";

export const data: PriceItem[] = [
  {
    name: "Taniec dla 4–6 latków + balet",
    price: "230 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "4–6 lat",
    category: "kidsDance",
  },
  {
    name: "Taniec dla 4–6 latków + akrobatyka",
    price: "240 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "4–6 lat",
    category: "kidsDance",
  },
  {
    name: "Balet + akrobatyka",
    price: "240 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "",
    category: "ballet",
  },
  {
    name: "Young Generation + akrobatyka",
    price: "270 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "7–9 lat",
    category: "youngGeneration",
  },
  {
    name: "Podstawa + KPOP/akrobatyka",
    price: "320 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "",
    category: "foundation",
  },
  {
    name: "Podstawa + choreo",
    price: "320 zł",
    frequency: "-",
    trending: false,
    age: "",
    category: "foundation",
  },
  {
    name: "Podstawa + choreo + taniec współczesny",
    price: "380 zł",
    frequency: "-",
    trending: false,
    age: "",
    category: "foundation",
  },
  {
    name: "Podstawa + taniec współczesny + KPOP + akrobatyka",
    price: "420 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "",
    category: "foundation",
  },
  {
    name: "Podstawa + KPOP / akrobatyka / choreo open",
    price: "330 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "",
    category: "hiphop",
  },
  {
    name: "Taniec współczesny + partnerowanie akro",
    price: "300 zł",
    frequency: "1x/tyg",
    trending: false,
    age: "8–12 lat",
    category: "modernDance",
  },
  {
    name: "Taniec współczesny + partnerowanie akro",
    price: "380 zł",
    frequency: "2x/tyg + 1x/tyg",
    trending: false,
    age: "13–18 lat",
    category: "modernDance",
  },
];
