import type { Metadata } from "next";
import { Anton, Roboto_Condensed } from "next/font/google";
import "./globals.css";

const fontAnton = Anton({
  variable: "--anton",
  subsets: ["latin-ext"],
  weight: "400",
  fallback: ["system-ui", "Segoe UI", "Arial"],
});

const fontRoboto = Roboto_Condensed({
  variable: "--roboto-condensed",
  subsets: ["latin-ext"],
  fallback: ["system-ui", "Segoe UI", "Arial"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={`${fontAnton.variable} ${fontRoboto.variable} `}>
        {children}
      </body>
    </html>
  );
}
