import type { Metadata } from "next";
import { Anton, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/myComponents/themeProvider/ThemeProvider";
import { TooltipProvider } from "@/components/ui/tooltip";
import Navbar from "@/myComponents/navbar/Navbar";

const fontAnton = Anton({
  variable: "--anton",
  subsets: ["latin-ext"],
  weight: "400",
  fallback: ["system-ui", "Segoe UI", "Arial"],
});

const fontRoboto = Roboto_Condensed({
  variable: "--roboto-condensed",
  subsets: ["latin-ext"],
  fallback: ["system-ui", "Segoe UI", "Arial"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl" suppressHydrationWarning>
      <body
        className={`${fontAnton.variable} ${fontRoboto.variable} max-w-480 m-auto`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <TooltipProvider>
            <Navbar />
            {children}
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
